name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change Directory
        run: cd src

      - name: Create Love File
        run: |
          find . -type f \( -name "*.lua" -o -name "*.png" -o -name "*.mp3" -o -name "*.wav" -o -name "*.ase" \) -print | zip -@ miako.love

      - name: Build Web Version
        run: |
          npm install -g love.js
          love.js miako.love web -c -t "Miako"

      - name: Zip Web Build
        run: |
          cd web && zip -r ../web-build.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          files: |
            miako.love
            web-build.zip
