name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Love File
        run: |
          find . -type f \( -name "*.lua" -o -name "*.png" -o -name "*.mp3" -o -name "*.wav" \) -print | zip -@ miako.love

      - name: Build Web Version
        run: |
          npm install -g love.js
          love.js miako.love web -c

      - name: Zip Web Build
        run: |
          cd web && zip -r ../web-build.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Love File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./miako.love
          asset_name: miako.love
          asset_content_type: application/zip

      - name: Upload Web Build
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: web-build.zip
